
spool C:\Users\Alumno\Documents\bases\parte1.txt
REM PAG 9 DE DEPENDENCIAS FUNCIONALES
REM PROF. DEMIAN GUTIERREZ MAKE_REFREM UNIVERSIDAD DE LOS ANDES VENEZUELA
REM CREMOS LA CANTIDAD CARRO
REM PROYECTAMOS LOS ATRIBUTOS PLACA, MARCA EN TABLA R
REM PROYECTAMOS LOS LOS ATRIBUTOS MARCA MODELO Y COLOR
REM QUITANDO TUPLAAS DUPLICADAS EN LA TABLA QUEUE

DROP TABLE CARRO;
CREATE TABLE CARRO (PLACA VARCHAR2 (6),
MARCA VARCHAR (6),
MODELO VARCHAR (8),
COLOR VARCHAR2(8));

INSERT INTO CARRO VALUES ('MBO34L','FORD','KA','VERDE');
INSERT INTO CARRO VALUES ('LDA75K','TOYOTA','COROLLA','BLANCO');
INSERT INTO CARRO VALUES ('ADA89A','FIAT','SIENA','GRIS');
INSERT INTO CARRO VALUES ('LBF78G','TOYOTA','COROLLA','BLANCO');
INSERT INTO CARRO VALUES ('XSA67','FORD','KA','ROJO');
SET PLACA, MARCA FROM CARRO ORDER BY 2;
DROP TABLE R;
CREATE TABLE R AS(
SELECT PLACA, MARA FROM CARRO)
ORDER BY 2;