REM EJERCICIO DEL CAPITULO 4 DEPENDENCIA FUNCIONALES
REM LIBRO MAIER PAG 43

DROP TABLE VUELOS;
CREATE TABLE VUELOS(
PILOT VARCHAR2(20),
FLIGHT NUMBER(3),
FECHA TIMESTAMP
);

INSERT INTO VUELOS VALUES('Lopez',83,TO_DATE('09/08/2018 10:15:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Gutierrez',83,TO_DATE('10/08/2018 10:15:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('chavez',116,TO_DATE('10/08/2018 13:25:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Lopez',281,TO_DATE('08/08/2018 5:50:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Lopez',301,TO_DATE('12/08/2018 18:35:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Lopez',83,TO_DATE('11/08/2018 10:15:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Romero',83,TO_DATE('13/08/2018 10:15:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Romero',116,TO_DATE('12/08/2018 13:25:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Cortes',281,TO_DATE('09/08/2018 5:50:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Cortes',281,TO_DATE('13/08/2018 5:50:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Cortes',412,TO_DATE('15/08/2018 13:25:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Bustamante',83,TO_DATE('15/08/2018 10:15:00','DD/MM/YYYY HH24:MI:SS'));
INSERT INTO VUELOS VALUES('Bustamante',83,TO_DATE('14/08/2018 10:15:00','DD/MM/YYYY HH24:MI:SS'));

SELECT FLIGHT VUELO, PILOT PILOTO, TO_CHAR(FECHA, 'DD/MM/YYYY HH24:MI:SS') FECHA
FROM VUELOS;

REM ORDENADOS POR  VUELO
SELECT FLIGHT VUELO, PILOT PILOTO, TO_CHAR(FECHA, 'DD/MM/YYYY HH24:MI:SS PM') FECHA
FROM VUELOS
ORDER BY 1;

REM CONFIGURA PAG Y LINEA

SET COLSEP'||'
COLUMN FECHA FORMAT A27
COLUMN HORAS_MIN FORMAT A15
SELECT FLIGHT VUELO, PILOT PILOTO, TO_CHAR(FECHA, 'DD/MM/YYYY') FECHA,
CONCAT(EXTRACT(HOUR FROM FECHA)||':', EXTRACT(MINUTE FROM FECHA)) HORAS_MIN
FROM VUELOS
ORDER BY 1;

REM ORDENAR POR HORA DE SALIDA
SELECT FLIGHT VUELO, PILOT PILOTO, TO_CHAR(FECHA, 'DD/MM/YYYY') FECHA,
CONCAT(EXTRACT(HOUR FROM FECHA)||':', EXTRACT(MINUTE FROM FECHA)) HORAS_MIN
FROM VUELOS
ORDER BY 4;

REM SOLO DESPLEGANDO EL NO DE VUELO Y LA HORA
SELECT PILOT PILOTO, TO_CHAR(FECHA, 'DD/MM/YYYY') FECHA, FLIGHT VUELO,
CONCAT(EXTRACT(HOUR FROM FECHA)||':', EXTRACT(MINUTE FROM FECHA)) HORAS_MIN
FROM VUELOS
ORDER BY 4;

REM DESPLEGANDO PRIMERO HORA Y LUEGO EL VUELO
SELECT PILOT PILOTO, TO_CHAR(FECHA, 'DD/MM/YYYY') FECHA, CONCAT(EXTRACT(HOUR FROM FECHA)||':', EXTRACT(MINUTE FROM FECHA)) HORAS_MIN,
FLIGHT VUELO
FROM VUELOS
ORDER BY 3;

REM PREGUNTA.... LA HORA DE SALIDA DETERMINA EL NUMERO DE VUELO?
REM PREGUNTA.... EL VUELO DETERMINA LA HORA DE SALIDA?

TIME FUNCTIONALY DEPENDS ON FLIGHT
FLIGHT FUNCTIONALY DEPENDS ON {PILOT,DATE,TIME} AND
PILOT FUNCTIONALY DEPENDS ON {FLIGHT,DATE}

SATISFIES TEST IF A RELATION SATIFIES AN FD X->Y