spool G:\ESCOM\bases\15_feb_18_queries\q7.txt
PROMPT DESPLIEGA LOS ATRIBUTOS ID_ NOMBRE DEPTO, MANAGER Y UBICACION
COLUMN Num format a21
column Nombre|depto format a21
column GERENTE FORMAT 9999
COLUMN LUGAR FORMAT 9999
SELECT DEPARTAMENT_ID "Num",departament_name "Nombre1depto", 
MANAGER_ID GERENTE, LOCATION_ID LUGAR
FROM DEPARTAMENTS 
WHERE MANAGER_ID IS NOT NULL
ORDER BY 2;
spool off