spool D:\ESCOM\bases\21_feb_18\spools\tablas_paso-3.txt
PROMPT PASO 3

ROLLBACK;

UPDATE CONTINENTE
SET Nom_CONTINENTE='IFRIQIYAAHI'
WHERE Nom_CONTINENTE='AFRICA';

UPDATE PAIS
SET CONTINENTE='IFRIQIYAAHI'
WHERE CONTINENTE='AFRICA';
spool off